---
- name: Set target for new finder windows
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfLo
  notify:
    - killall Finder

- name: Set path for new finder windows
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: file://${HOME}
  notify:
    - killall Finder

- name: Show icons for Hard Drives on Desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true
  notify:
    - killall Finder

- name: Show icons for External Hard Drives on Desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true
  notify:
    - killall Finder

- name: Show icons for mounted servers on Desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true
  notify:
    - killall Finder

- name: Show icons for removable media on Desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true
  notify:
    - killall Finder

- name: Show path bar in finder
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  notify:
    - killall Finder

- name: Keep folders on top when sorting by name
  osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  notify:
    - killall Finder

- name: When performing a search, search the current folder by default
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf
  notify:
    - killall Finder

- name: Disable the warning when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  notify:
    - killall Finder

- name: Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Avoid creating .DS_Store files on USB volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: false

- name: Show the ~/Library folder
  command: chflags nohidden ~/Library

- name: Show the /Volumes folder
  command: chflags nohidden /Volumes