---
- name: Privacy - don’t send search queries to Apple
  osx_defaults:
    domain: com.apple.Safari
    key: UniversalSearchEnabled
    type: bool
    value: false
  notify:
  - killall Dock

- name: Privacy - don’t send search queries to Apple
  osx_defaults:
    domain: com.apple.Safari
    key: SuppressSearchSuggestions
    type: bool
    value: false
  notify:
    - killall Dock

- name: Hide bookmarks bar in Safari by default
  osx_defaults:
    domain: com.apple.Safari
    key: ShowFavoritesBar
    type: bool
    value: false
  notify:
    - killall Dock

- name: Enable Safari's debugging menu
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true
  notify:
    - killall Dock

- name: Enable the Develop menu and the Web Inspector in Safari
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeDevelopMenu
    type: bool
    value: true
  notify:
    - killall Dock

- osx_defaults:
    domain: com.apple.Safari
    key: WebKitDeveloperExtrasEnabledPreferenceKey
    type: bool
    value: true
  notify:
    - killall Dock

-  osx_defaults:
    domain: com.apple.Safari
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
    type: bool
    value: true
  notify:
    - killall Dock

- name: Enable "Do Not Track"
  osx_defaults:
    domain: com.apple.Safari
    key: SendDoNotTrackHTTPHeader
    type: bool
    value: true
  notify:
    - killall Dock